### ISSUE TITLE
Capture params needed by AutoTest container

### ISSUE THREAD

**Issue by rtholmes** [ubccpsc/classy#19]
@nickbradley : `AutoTestRoutes::atContainerDetails` is supposed to return fields needed by the AutoTest from portal-backend. If you have any guidance as to what info you actually need to spin up the container, let me know. Right now it returns:

```
/**
 * AutoTest configuration details.
 * Requested per-deliverable.
 */
export interface AutoTestConfigTransport {
    dockerImage: string,
    studentDelay: number, // interval in seconds between student requests
    maxExecTime: number, // max time container can try to execute tests for
    regressionDelivIds: string[]
}
```

Here we have to balance putting things in `.env` against building UI for them in the Admin Portal. Other than `maxExec` though I could be convinced to include them all in the Deliverables UI. Thoughts? (or any fields missing?)

**Comment by nickbradley** [comment]
@rtholmes: Just reviewing the code, I'll need
- dockerImage
- maxExecTime
- assignment/deliverable ID
- student project URL (and a GH token with read permission to clone)

all of which it looks like will be available. In terms of the `.env`, I would push to have it contain only service-level information like ports and directories. Everything for the service logic should be served from portal-backend, otherwise it becomes less clear where the config info is coming from. Since I expect most of the config will be static for the term, maybe there doesn't need to be a GUI for those fields yet? (Why don't you want `maxExec` in the Admin Portal?)

**Comment by rtholmes** [comment]
It's just a matter of building a UI. But providing those four fields should be easy. Is your `deliverable ID` above the default deliverable name for a deliverable, or just the one that AutoTest invokes the container with?

**Comment by nickbradley** [comment]
It would be the ID that AutoTest invokes the container with.

**Comment by rtholmes** [comment]
That's ok then, that will come from the `ICommentEvent` so it is already supported.
