### ISSUE TITLE
Use student preferred names in classy

### ISSUE THREAD

**Issue by wilbowma** [ubccpsc/classy#330]
When generating a report, a TA got a complaint that a student's data was using their legal name instead of their preferred name. Can we add a preferred names column?

**Comment by winstan** [comment]
Simple solution: Don't use name at all. Build reports that key on ID rather than name.

PREF is available in classlist, and there are a number of possibilities...
If you import your own classlist manually (instead of using the automatic button), you could use PREF and relabel it FIRST in the csv before uploading.
We could change the classlist importer altogether and have it look for PREF instead of FIRST.

Any of the above is better (IMO) than adding another column. Frankly, I can't see any of the current users of Classy agreeing to another column...

**Comment by winstan** [comment]
Let's (@andrewstec) take a crack at adjusting Classy to prioritize PREF over FIRST in classlist imports. So if PREF exists, use it for first name, otherwise use FIRST.

@rtholmes, what do you think of this?

**Comment by andrewstec** [comment]
@rtholmes FIRST and LAST were the only options in Classlist before, but now PREF will be available via the API import.

**Comment by winstan** [comment]
(PREF is already in the API import.)

**Comment by rtholmes** [comment]
@andrewstec go for it. Names aren't used anywhere as keys anyways, they're just displayed for users. It totally makes sense to use the preferred name if it is present.

**Comment by andrewstec** [comment]
@rtholmes Sounds great! We will make the change. Thanks!

**Comment by andrewstec** [comment]
@wilbowma

FYI: https://github.com/ubccpsc/classy/pull/338

**Comment by andrewstec** [comment]
Portal has been programmed to take the preferred name over the first name field. The preferred name is available in the API integration, so it can be imported automatically by updating the class list in the admin area. User first names will be overwritten by the classlist update.

If you need to use first names instead of preferred names for whatever reason, you will have to manually create a CSV and ONLY include the FIRST name field.
