### ISSUE TITLE
Calls on old provisioned repos are not being ignored

### ISSUE THREAD

**Issue by falkirks** [ubccpsc/classy#363]
In CPSC 310 last term a student accidently called autobot on a repo that has been provisioned for them in a previous term instead of their current term. 

The expected behaviour would be for autobot to ignore the webhook event as it corresponds to a non-current term. 

Instead autobot was called normally, returning a grade, and the grade entry for that previous term repo was reported into classy under the current team with that number.

**Comment by andrewstec** [comment]
Thank you for letting us know that this issue can occur. We may remove the students from the organization after the semester ends to eliminate this possibility. This would require an operations change instead of any bug fixes.

I will let you know once we are going a particular approach. I have to mull this over and see if we can eliminate repository access to students after a semester ends.

**Comment by winstan** [comment]
I don't think we can unilaterally remove students completely from all Classy organizations. I can't see all instructors agreeing to that. However, there could be some process to remove write access for students...

**Comment by andrewstec** [comment]
I'm more inclined to agree with @falkirks then, as building this logic into the application would allow us to manage less from an operations perspective.
