### ISSUE TITLE
Do customizations via 'plug-in'

### ISSUE THREAD

**Issue by winstan** [ubccpsc/classy#372]
We need to move from the model of:
every user has their own fork
to:
every user uses the main repo and customizes with a plugin.

Like what's in PR #368 (but inverted).

We'll need:
1. Plugin interface documentation
2. Defaults when no plugin

The current mechanism for changing classy behavior should be removed in favor of the new plugin code. We do not want to support both.

**Comment by andrewstec** [comment]
@winstan Just to clarify, Reid mentioned that running Classy with the defaults, aka. without a plugin, makes it tempting to fork and modify Classy. (Based on his experience)

I can imagine that some software developers might have this problem. Are we still happy to nonetheless make Classy run without any plugins? I just want to make sure that we caught that concern.

I know you mentioned that we can use the old Classy project code to run Classy until classes are brought up to speed. However, if we were to do that, it would be because Classy does not run with the defaults at runtime.

Hence, I just wanted to clarify. Should Classy run with the default views if no plugin is available? This issue makes it seem like it should. I can go either way here.

**Comment by winstan** [comment]
Yes, Classy should run with the default views if no plugin is available.

The key difference is that currently, you HAVE to fork to make any changes, even the ones you're 'allowed' to make. Once you've forked and are making changes to things, it's simply too easy to just make changes to other things and commit to your forked repo - nothing will complain.
Now, if standard procedure is to use the main branch of the original repo, then it takes much more effort to keep any changes you make to Classy core - they won't commit with all the rest of your course customizations.
Furthermore, it is simple to ensure that all supported courses actually use the main classy (long-term anyways) without needing to know everything about their specific changes.

Is that clear enough?

**Comment by andrewstec** [comment]
> Yes, Classy should run with the default views if no plugin is available.
> 
> The key difference is that currently, you HAVE to fork to make any changes, even the ones you're 'allowed' to make. Once you've forked and are making changes to things, it's simply too easy to just make changes to other things and commit to your forked repo - nothing will complain.
> Now, if standard procedure is to use the main branch of the original repo, then it takes much more effort to keep any changes you make to Classy core - they won't commit with all the rest of your course customizations.
> Furthermore, it is simple to ensure that all supported courses actually use the main classy (long-term anyways) without needing to know everything about their specific changes.
> 
> Is that clear enough?

Yep. Works!

**Comment by winstan** [comment]
This was done in https://github.com/ubccpsc/classy/pull/376
